#!/usr/bin/env python3
"""Generate the dashboard's flash map from the firmware partition table.

Source: firmware/esp32_robot_idf/partitions.csv (the single source of truth;
every board's platformio env flashes this same table).
Output: docs/ide/flash-map.js — `export const FLASH_MAP = [...]`

The IDE's Firmware panel shows the flash layout. Deriving it here instead of
hardcoding a JS copy (or shipping it over BLE in fw_info, which overflowed the
read) keeps it from drifting: the pre-commit hook regenerates and fails if the
CSV changed without this being updated. Run `make gen-partitions` or via
`make gen` / the firmware compile.
"""
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(REPO_ROOT, "firmware", "esp32_robot_idf", "partitions.csv")
OUT = os.path.join(REPO_ROOT, "docs", "ide", "flash-map.js")


def parse_num(s):
    """Partition CSV offsets/sizes: hex (0x...), or K/M-suffixed."""
    s = s.strip()
    if s[-1:].lower() == "k":
        return int(s[:-1], 0) * 1024
    if s[-1:].lower() == "m":
        return int(s[:-1], 0) * 1024 * 1024
    return int(s, 0)


def rows():
    with open(SOURCE) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            cols = [c.strip() for c in line.split(",")]
            if len(cols) < 5:
                continue
            name, ptype, subtype, offset, size = cols[:5]
            yield name, ptype, subtype, parse_num(offset), parse_num(size)


def write_if_changed(path, content):
    if os.path.exists(path):
        with open(path) as f:
            if f.read() == content:
                return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    return True


def main():
    lines = [
        "// Generated by tools/gen-partitions.py from"
        " firmware/esp32_robot_idf/partitions.csv — do not edit.\n",
        "// Run `make gen-partitions` after editing the partition table.\n\n",
        "export const FLASH_MAP = [\n",
    ]
    for name, ptype, subtype, offset, size in rows():
        lines.append(
            f'  {{ label: "{name}", type: "{ptype}", subtype: "{subtype}",'
            f" offset: {offset}, size: {size} }},\n"
        )
    lines.append("];\n")
    if write_if_changed(OUT, "".join(lines)):
        print("updated docs/ide/flash-map.js")
    else:
        print("flash-map: up to date")


if __name__ == "__main__":
    sys.exit(main())
